# Generated by Django 3.2.6 on 2021-08-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm', '0002_product_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(max_length=255, null=True, upload_to='productPictures'),
        ),
    ]
